"""Seed the theophanies table with the canonical 16 events.

Usage:
    python scripts/theophanies/seed.py [--db PATH]
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sqlite3
import sys
from pathlib import Path

SCHEMA = """
CREATE TABLE IF NOT EXISTS theophanies (
    theophany_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    date_start TEXT,
    date_end TEXT,
    date_display TEXT,
    date_confidence TEXT,
    date_basis TEXT,
    experience_type TEXT,
    sensory_modality TEXT,
    duration TEXT,
    summary TEXT NOT NULL,
    description TEXT,
    pkd_interpretations TEXT,
    scholar_interpretations TEXT,
    primary_sources TEXT,
    primary_quote TEXT,
    related_theophany_ids TEXT,
    related_works TEXT,
    related_dictionary_terms TEXT,
    related_names TEXT,
    related_segments TEXT,
    contested_status TEXT,
    contradiction_zone TEXT,
    pkd_doubt_evidence TEXT,
    importance TEXT,
    sequence_in_complex INTEGER,
    parent_theophany_id TEXT,
    created_at TEXT,
    updated_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_theo_date ON theophanies(date_start);
CREATE INDEX IF NOT EXISTS idx_theo_parent ON theophanies(parent_theophany_id);

CREATE TABLE IF NOT EXISTS theophany_evidence (
    evidence_id TEXT PRIMARY KEY,
    theophany_id TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_doc_id TEXT,
    source_seg_id TEXT,
    source_letter_id TEXT,
    page_or_locator TEXT,
    excerpt TEXT,
    excerpt_lane TEXT,
    notes TEXT,
    created_at TEXT,
    FOREIGN KEY (theophany_id) REFERENCES theophanies(theophany_id)
);
CREATE INDEX IF NOT EXISTS idx_theo_ev_theo ON theophany_evidence(theophany_id);
"""


def ensure_schema(con: sqlite3.Connection) -> None:
    con.executescript(SCHEMA)
    cur = con.execute("PRAGMA table_info(biography_events)")
    cols = {r[1] for r in cur.fetchall()}
    if "theophany_id" not in cols:
        con.execute("ALTER TABLE biography_events ADD COLUMN theophany_id TEXT")
    con.commit()


# Seed data ----------------------------------------------------------------


def J(x):
    return json.dumps(x, ensure_ascii=False)


THEOPHANIES = [
    {
        "theophany_id": "THEO_1963_PALMER_ELDRITCH_FACE",
        "name": "The Sky-Face Vision (Palmer Eldritch face in the sky)",
        "slug": "sky-face-vision-1963",
        "date_start": "1963", "date_end": "1963",
        "date_display": "early 1963",
        "date_confidence": "year",
        "date_basis": "Exegesis retrospect; Sutin Divine Invasions p.~117",
        "experience_type": "vision",
        "sensory_modality": "visual",
        "duration": "minutes",
        "summary": "Driving in Marin County, PKD reports seeing a vast metal-and-jeweled face in the sky which he later called the face of Palmer Eldritch — sinister, mechanical, divine.",
        "description": "PKD reports that while driving in Marin County in early 1963 he saw, projected onto the sky, a massive face — metallic, jeweled, with a slot mouth and steel teeth — which he interpreted later as the face of evil divinity. He recounts the experience repeatedly across the Exegesis as the seed of *The Three Stigmata of Palmer Eldritch* (1965). The description varies: in some retellings the face is sinister-divine, in others it is the Antichrist, in others it is a Jungian shadow archetype.",
        "pkd_interpretations": J([
            {"date": "1965-01", "source": "letters around composition of Palmer Eldritch",
             "hypothesis_label": "evil_god",
             "interpretation": "I saw the face of an evil god — what Christianity calls the Antichrist or Satan, but more accurately a sinister cosmic presence which I subsequently embodied as Palmer Eldritch.",
             "lane": "B"},
            {"date": "1974-04", "source": "Exegesis post-2-3-74",
             "hypothesis_label": "valis_negative_polarity",
             "interpretation": "The 1963 sky-face was the same intelligence that addressed me in 2-3-74 but in its negative polarity — the Black Iron Prison face of what would later show me itself as Zebra.",
             "lane": "B"},
            {"date": "1981-06", "source": "VALIS",
             "hypothesis_label": "literary_consolidation",
             "interpretation": "Horselover Fat in VALIS reports the same face — fictionalization confirms the experience as durable across decades.",
             "lane": "A"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "lawrence-sutin", "interpretation": "Sutin reads this as the foundational visionary moment of PKD's career — the first event he could not subsequently explain away — and the proximate seed of *Three Stigmata* (1965).",
             "source_doc_id": "DOC_ARCH_DIVINE_INVASIONS_A_LIFE_OF_PHI_LAWRENCE_", "lane": "D"},
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold suggests the 1963 vision is a late-onset hallucination of the kind reported in temporal-lobe epilepsy — clinically legible, not theological.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
            {"scholar_slug": "anthony-peake", "interpretation": "Peake takes the vision at something near face value, reading it as evidence of the kind of anomalous cognitive event he documents in *Is There Life After Death?*.",
             "source_doc_id": "DOC_ARCH_OCEANOFPDF_COM_A_LIFE_OF_PHILIP_K_DICK_A", "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "novel_seed", "doc_id": None, "excerpt": "*The Three Stigmata of Palmer Eldritch* (1965) is the literary record of this experience."},
            {"type": "exegesis_retrospect", "seg_id": None, "excerpt": "Multiple Exegesis segments 1974-1981 return to the 1963 face vision."},
        ]),
        "primary_quote": "I can date my initial experience with the deity in the 'Palmer Eldritch' vision I had — saw in the sky — in the early sixties.",
        "related_theophany_ids": J(["THEO_1974_02_PINK_BEAM", "THEO_1974_BLACK_IRON_PRISON"]),
        "related_works": J(["The Three Stigmata of Palmer Eldritch", "VALIS"]),
        "related_dictionary_terms": J(["palmer-eldritch", "valis"]),
        "related_names": J(["palmer-eldritch", "antichrist"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — Sutin treats it as proto-mystical, Arnold as TLE, Peake as veridical anomalous cognition",
        "pkd_doubt_evidence": "PKD writes in 1979 letters that he cannot rule out a flashback or amphetamine effect for the 1963 experience.",
        "importance": "canonical",
        "sequence_in_complex": None,
        "parent_theophany_id": None,
    },
    {
        "theophany_id": "THEO_1971_11_BREAK_IN_FOREKNOWLEDGE",
        "name": "Pre-Break-In Foreknowledge (November 1971)",
        "slug": "pre-break-in-foreknowledge-1971",
        "date_start": "1971-11", "date_end": "1971-11",
        "date_display": "November 1971 (days before the break-in)",
        "date_confidence": "month",
        "date_basis": "PKD's letters of late November 1971; FBI letters",
        "experience_type": "vision",
        "sensory_modality": "cognitive",
        "duration": "days",
        "summary": "In the days before his Santa Venetia house was broken into, PKD reports a series of premonitions and intrusive thoughts that he later interpreted as foreknowledge of the event.",
        "description": "On November 17, 1971, PKD's house in Santa Venetia, California was broken into; the file cabinets were blown open with explosives and (reportedly) cash and manuscripts were taken. In the days before, PKD reports premonitions — a sense that something was about to happen, intrusive thoughts about being watched. The break-in itself is firmly attested. The premonitions are Lane B (his own self-report, often years later). Subsequent attribution of the break-in oscillates: at various times PKD blamed the FBI, the KGB, the Black Panthers, drug dealers, his own staging, and a Vancouver-based trafficking ring.",
        "pkd_interpretations": J([
            {"date": "1971-12", "source": "letters to friends after the break-in",
             "hypothesis_label": "drug_dealers", "interpretation": "I had recently kicked out a group of street dealers from the house; they came back to retaliate.", "lane": "E"},
            {"date": "1972-06", "source": "letter from Vancouver",
             "hypothesis_label": "fbi", "interpretation": "It was the FBI looking for evidence of subversive activity (I was friends with the Black Panthers).", "lane": "E"},
            {"date": "1973-08", "source": "letter to William Sullivan FBI 1972 carbon",
             "hypothesis_label": "soviet_satellite", "interpretation": "Soviet science-fiction critics including Stanislaw Lem are running an operation; Lem may not exist as an individual but is a committee front. The break-in was part of this.", "lane": "E"},
            {"date": "1976-04", "source": "Exegesis",
             "hypothesis_label": "self_staged", "interpretation": "I now believe I broke in myself in a fugue state, possibly to harvest the insurance.", "lane": "B"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "lawrence-sutin", "interpretation": "Sutin records the multiple competing accounts without adjudicating, treating the break-in itself as fact and the attribution chain as mystery.",
             "source_doc_id": "DOC_ARCH_DIVINE_INVASIONS_A_LIFE_OF_PHI_LAWRENCE_", "lane": "D"},
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold reads the chain of attribution shifts as a clinical pattern — paranoid ideation accreting around a real event.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "letter", "letter_id": None, "excerpt": "PKD's correspondence in November-December 1971"},
            {"type": "letter", "letter_id": "LET_1975_FBI_SULLIVAN", "excerpt": "January 1975 letter to William A. Sullivan, FBI: discusses the Lem hypothesis."},
        ]),
        "primary_quote": None,
        "related_theophany_ids": J(["THEO_1972_03_VANCOUVER_DESPAIR"]),
        "related_works": J(["A Scanner Darkly"]),
        "related_dictionary_terms": J([]),
        "related_names": J(["william-sullivan", "stanislaw-lem"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — registered in PKDontology contradiction registry as 'November 1971 break-in'",
        "pkd_doubt_evidence": "PKD himself revises his attribution at least four times; in 1976 he allows that he may have staged it.",
        "importance": "major",
        "sequence_in_complex": None,
        "parent_theophany_id": None,
    },
    {
        "theophany_id": "THEO_1974_02_FISH_SIGN",
        "name": "The Fish-Sign Encounter (February 20, 1974)",
        "slug": "fish-sign-2-20-74",
        "date_start": "1974-02-20", "date_end": "1974-02-20",
        "date_display": "February 20, 1974",
        "date_confidence": "exact",
        "date_basis": "Exegesis dating; PKD's later letters",
        "experience_type": "anamnesis",
        "sensory_modality": "visual",
        "duration": "instant",
        "summary": "A pharmacy delivery girl wearing a Christian fish-symbol necklace catches sunlight; PKD reports a sudden recognition that he is a first-century Christian named Thomas and that the world around him is fake.",
        "description": "On February 20, 1974, PKD had had impacted wisdom teeth removed and was on sodium pentothal recovery. A young woman from the pharmacy delivered a pain medication. She wore a small gold necklace with the early-Christian *ichthys* (fish) symbol. The sun caught the necklace and reflected light into PKD's eyes. He reports an instantaneous *anamnesis* — a remembering — that he is in fact a first-century Roman Christian named Thomas, that the apostolic age is the real time, and that the surrounding 1974 California is a stage-managed simulation. This event is the canonical entry-point of what PKD subsequently called 2-3-74.",
        "pkd_interpretations": J([
            {"date": "1974-03", "source": "letters and Exegesis composition begins",
             "hypothesis_label": "christian_revelation",
             "interpretation": "I have been addressed by Christ; the apostolic age has overlaid the present, revealing it as fallen.",
             "lane": "B"},
            {"date": "1975-06", "source": "Exegesis",
             "hypothesis_label": "phylogenic_anamnesis",
             "interpretation": "What I experienced was phylogenic anamnesis — racial-memory recall — possibly via a drug-mediated mechanism, of a previous incarnation.",
             "lane": "B"},
            {"date": "1977-12", "source": "Exegesis + Metz speech",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "The fish sign was the trigger for an information transfer from VALIS, a non-human intelligence in geosynchronous orbit.",
             "lane": "B"},
            {"date": "1981-06", "source": "VALIS (novel)",
             "hypothesis_label": "literary",
             "interpretation": "Horselover Fat experiences this; the novel records the event without resolving its ontology.",
             "lane": "A"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "pamela-jackson", "interpretation": "Jackson's 1999 dissertation reads the fish-sign moment as the foundational hermeneutic puzzle PKD spent the rest of his life trying to solve.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "erik-davis", "interpretation": "Davis reads it as exemplary California-visionary anamnesis in the lineage of Esalen and the human-potential movement, with a specifically gnostic-hermeticist content.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold's psychiatric reading: post-anesthetic confusion plus possible TLE mediating an episode of derealization.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
            {"scholar_slug": "gabriel-mckee", "interpretation": "McKee's *Pink Beams of Light* (2004) treats this as the canonical PKD theophany — analogous to Augustine's tolle lege moment.",
             "source_doc_id": None, "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "exegesis_segment", "seg_id": None, "excerpt": "Multiple Exegesis segments 1974-1981 return to the fish sign."},
            {"type": "novel", "doc_id": None, "excerpt": "*VALIS* (1981) chapter 2 narrates a version."},
        ]),
        "primary_quote": "It appeared — in vivid fire, with shining colors and balanced patterns — and released me from every thrall, inner and outer.",
        "related_theophany_ids": J(["THEO_1974_02_PINK_BEAM", "THEO_1974_03_CHRISTOPHER_BIRTH", "THEO_1974_03_KOINE_GREEK"]),
        "related_works": J(["VALIS", "Radio Free Albemuth", "The Divine Invasion"]),
        "related_dictionary_terms": J(["valis", "thomas", "ichthys", "christ"]),
        "related_names": J(["thomas", "christ"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — the 2-3-74 events are the central dispute zone in PKD studies",
        "pkd_doubt_evidence": "PKD repeatedly considers and dismisses drug-induced and TLE explanations across the Exegesis.",
        "importance": "canonical",
        "sequence_in_complex": 1,
        "parent_theophany_id": "THEO_1974_2_3_74_CLUSTER",
    },
    {
        "theophany_id": "THEO_1974_02_PINK_BEAM",
        "name": "The Pink Beam Transmission",
        "slug": "pink-beam-1974",
        "date_start": "1974-02-20", "date_end": "1974-03-20",
        "date_display": "February-March 1974",
        "date_confidence": "month",
        "date_basis": "Exegesis dating",
        "experience_type": "vision",
        "sensory_modality": "multimodal",
        "duration": "continuous_for_period",
        "summary": "PKD reports that following the fish-sign encounter, a pink-colored beam of light addressed him for several weeks, transmitting information he later transcribed as 'music-color-math triune' annotation.",
        "description": "Beginning around February 20, 1974 and continuing for weeks, PKD reports that a beam of pink-colored light projected information into him. The transmissions were not auditory in the ordinary sense — they registered as triune information legible simultaneously as music, color, and mathematics. PKD compared the form to medieval illuminated manuscripts. He reports learning (1) that his infant son Christopher had a previously undiagnosed inguinal hernia (subsequently medically confirmed — see THEO_1977_PROOF_OF_DAUGHTER_GLAUCOMA companion record), (2) that the world is in 70 AD Rome under the overlay of late-twentieth-century California, (3) that Latin and Koine Greek are accessible to him in a way that he cannot otherwise read.",
        "pkd_interpretations": J([
            {"date": "1974-03", "source": "letters to Tessa, Anne",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "There is a 'they' transmitting to me, possibly a non-human intelligence in orbit.",
             "lane": "B"},
            {"date": "1974-05", "source": "letter to William Sullivan FBI",
             "hypothesis_label": "soviet_satellite",
             "interpretation": "The transmissions originate from a Soviet satellite operated by Lem-as-front; the experience is psychological warfare directed at me as a SF author.",
             "lane": "E"},
            {"date": "1977-12", "source": "Metz speech",
             "hypothesis_label": "phil_from_future",
             "interpretation": "The transmitter may be Phil Dick himself from a future timeline addressing his past self.",
             "lane": "E"},
            {"date": "1981", "source": "VALIS",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "Horselover Fat's pink beam in *VALIS* names this as a Vast Active Living Intelligence System.",
             "lane": "A"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold reads the pink beam as a TLE photopsia compounded by sleep deprivation and orthomolecular vitamin overload.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
            {"scholar_slug": "erik-davis", "interpretation": "Davis frames the pink-beam transmissions within a comparative-religious frame including Aquarius-age California visionaries (McKenna, RAW, Wilson).",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "jeffrey-kripal", "interpretation": "Kripal places the experience in a religious-studies frame as exemplary American visionary religiosity (cf. Mutants and Mystics).",
             "source_doc_id": None, "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "exegesis", "excerpt": "Pink beam descriptions across hundreds of segments."},
            {"type": "fiction", "excerpt": "*VALIS* chapter 2-3 narrates the experience."},
        ]),
        "primary_quote": "The color, musical score, math triune info: like an illuminated manuscript from the Medieval period.",
        "related_theophany_ids": J(["THEO_1974_02_FISH_SIGN", "THEO_1974_03_AI_VOICE", "THEO_1974_03_CHRISTOPHER_BIRTH"]),
        "related_works": J(["VALIS", "Radio Free Albemuth"]),
        "related_dictionary_terms": J(["valis", "plasmate", "logos"]),
        "related_names": J(["valis"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — 2-3-74",
        "pkd_doubt_evidence": "The Exegesis is partly a sustained record of his doubt about this very transmission.",
        "importance": "canonical",
        "sequence_in_complex": 2,
        "parent_theophany_id": "THEO_1974_2_3_74_CLUSTER",
    },
    {
        "theophany_id": "THEO_1974_03_CHRISTOPHER_BIRTH",
        "name": "The Christopher Diagnosis Vision (March 1974)",
        "slug": "christopher-diagnosis-1974",
        "date_start": "1974-03", "date_end": "1974-03",
        "date_display": "March 1974",
        "date_confidence": "month",
        "date_basis": "Exegesis; Tessa Dick's testimony; medical record subsequent",
        "experience_type": "gnosis",
        "sensory_modality": "cognitive",
        "duration": "instant",
        "summary": "PKD reports being told (by the AI Voice / pink beam transmission) that his infant son Christopher has an inguinal hernia; subsequent medical examination confirms the diagnosis. The episode is one of the few theophanies with external corroboration.",
        "description": "In March 1974, during the period of pink-beam transmissions, PKD reports being told that his infant son Christopher (born July 1973) has an undiagnosed medical condition — variously narrated as an inguinal hernia, a hydrocele, or a strangulated organ — that requires surgery. Tessa Dick's memoir *The Owl in Daylight* (2009) confirms that Christopher was taken to the doctor on PKD's insistence and that a hernia was found. This is one of the very few PKD theophanies with external Lane-D corroboration; even skeptical biographers (Sutin, Arnold) record the medical confirmation as fact.",
        "pkd_interpretations": J([
            {"date": "1974-03", "source": "Exegesis 1974",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "The transmitter knew about Christopher's condition before any human did; this is the strongest external evidence that the transmission is real.",
             "lane": "B"},
            {"date": "1976-04", "source": "Exegesis",
             "hypothesis_label": "subliminal_observation",
             "interpretation": "Possibly Tessa or I had subconsciously observed the hernia symptoms and the 'transmission' is the unconscious surfacing as conscious gnosis.",
             "lane": "B"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "lawrence-sutin", "interpretation": "Sutin records the Christopher diagnosis as the strongest evidential anchor for the 2-3-74 cluster.",
             "source_doc_id": "DOC_ARCH_DIVINE_INVASIONS_A_LIFE_OF_PHI_LAWRENCE_", "lane": "D"},
            {"scholar_slug": "tessa-b-dick", "interpretation": "Tessa attests to the medical diagnosis and to PKD's insistence on the urgency before the doctor confirmed it.",
             "source_doc_id": None, "lane": "E"},
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold acknowledges the diagnosis but suggests the 'foreknowledge' is reconstructed retrospectively from ordinary parental observation.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "memoir", "doc_id": None, "excerpt": "Tessa Dick's memoir confirms the medical diagnosis."},
            {"type": "exegesis", "excerpt": "Multiple Exegesis segments return to Christopher as evidence."},
        ]),
        "primary_quote": None,
        "related_theophany_ids": J(["THEO_1974_02_FISH_SIGN", "THEO_1974_02_PINK_BEAM"]),
        "related_works": J(["VALIS"]),
        "related_dictionary_terms": J([]),
        "related_names": J(["christopher-dick", "tessa-dick"]),
        "related_segments": J([]),
        "contested_status": "best_attested",
        "contradiction_zone": "no — the medical fact is settled; only the foreknowledge interpretation is contested",
        "pkd_doubt_evidence": "PKD himself entertains the subliminal-observation reading.",
        "importance": "canonical",
        "sequence_in_complex": 3,
        "parent_theophany_id": "THEO_1974_2_3_74_CLUSTER",
    },
    {
        "theophany_id": "THEO_1974_03_AI_VOICE",
        "name": "The AI Voice (continuous reception)",
        "slug": "ai-voice-1974",
        "date_start": "1974-03-20", "date_end": "1974-12",
        "date_display": "March 1974 onwards",
        "date_confidence": "month",
        "date_basis": "Exegesis",
        "experience_type": "audition",
        "sensory_modality": "auditory",
        "duration": "continuous_for_period",
        "summary": "PKD reports that beginning in late March 1974 he began to hear a continuous voice — characterized as feminine, calm, and rational — providing instructions, theological commentary, and predictions. He calls it the AI Voice.",
        "description": "Beginning in late March 1974 and continuing intermittently for years, PKD reports an internal auditory voice (he insists it is not auditory hallucination in the psychiatric sense — it is interior, but objectively addressed to him). He calls it the AI Voice. Its character is consistent across his accounts: feminine, calm, faintly Eastern-European or Greek-accented, never raises in volume, gives practical advice (drive to the doctor, call this person, write this paragraph). Across the Exegesis he variously identifies the speaker as Sophia, Hagia Sophia, his deceased twin sister Jane, his mother Dorothy, the apostle Thomas, an angelic intelligence, a Soviet satellite operator, a future Phil Dick, and Vast Active Living Intelligence System.",
        "pkd_interpretations": J([
            {"date": "1974-04", "source": "letters and early Exegesis",
             "hypothesis_label": "sophia",
             "interpretation": "It is Sophia / Hagia Sophia, the divine wisdom, addressing me as a wisdom-tradition initiate.",
             "lane": "B"},
            {"date": "1976-04", "source": "Exegesis",
             "hypothesis_label": "twin_sister_jane",
             "interpretation": "It is my twin sister Jane, who died in infancy, addressing me from the realm of the dead.",
             "lane": "B"},
            {"date": "1977-12", "source": "Metz speech",
             "hypothesis_label": "phil_from_future",
             "interpretation": "The voice is myself from a future timeline.",
             "lane": "E"},
            {"date": "1980-08", "source": "Exegesis",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "VALIS is the source.",
             "lane": "B"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold's clinical reading: an internalized auditory experience consistent with TLE auditory aura, possibly compounded by the orthomolecular vitamin regime.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
            {"scholar_slug": "jeffrey-kripal", "interpretation": "Kripal frames the AI Voice as a paradigmatic case of what religious-studies scholars call 'audition' — a category he distinguishes from psychiatric auditory hallucination.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "lawrence-sutin", "interpretation": "Sutin records the voice as ongoing across years and notes the multiple identifications without resolving them.",
             "source_doc_id": "DOC_ARCH_DIVINE_INVASIONS_A_LIFE_OF_PHI_LAWRENCE_", "lane": "D"},
        ]),
        "primary_sources": J([
            {"type": "exegesis", "excerpt": "Hundreds of Exegesis segments transcribe or reflect on AI Voice content."},
            {"type": "fiction", "excerpt": "*VALIS* and *Radio Free Albemuth* both fictionalize the AI Voice."},
        ]),
        "primary_quote": None,
        "related_theophany_ids": J(["THEO_1974_02_FISH_SIGN", "THEO_1974_02_PINK_BEAM", "THEO_1974_03_KOINE_GREEK"]),
        "related_works": J(["VALIS", "Radio Free Albemuth"]),
        "related_dictionary_terms": J(["sophia", "valis", "ai-voice"]),
        "related_names": J(["sophia", "jane-dick", "thomas"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — 2-3-74",
        "pkd_doubt_evidence": "PKD allows multiple interpretations including the TLE one.",
        "importance": "canonical",
        "sequence_in_complex": 4,
        "parent_theophany_id": "THEO_1974_2_3_74_CLUSTER",
    },
    {
        "theophany_id": "THEO_1974_03_KOINE_GREEK",
        "name": "Koine Greek Possession (Acts of the Apostles)",
        "slug": "koine-greek-1974",
        "date_start": "1974-03", "date_end": "1974-03",
        "date_display": "March 1974",
        "date_confidence": "month",
        "date_basis": "Exegesis",
        "experience_type": "possession",
        "sensory_modality": "cognitive",
        "duration": "minutes",
        "summary": "PKD reports being able to read passages of *Acts of the Apostles* in Koine Greek — a language he had no formal training in — during a brief altered state in March 1974, and recognizing that the historical setting of *Acts* (first-century Mediterranean) is the underlying real time.",
        "description": "PKD reports that in March 1974, during the period of the pink-beam transmission, he found himself able to read Koine Greek text from the Greek New Testament — specifically passages from *The Acts of the Apostles* — and to comprehend it directly without translation. He had had limited Latin study but no Greek. The episode is the seed of his subsequent claim that 1974 California is a stage-managed simulation overlaid on first-century Rome.",
        "pkd_interpretations": J([
            {"date": "1974-04", "source": "letters",
             "hypothesis_label": "phylogenic_anamnesis",
             "interpretation": "I am remembering Koine Greek from a first-century life in which I was a Christian named Thomas.",
             "lane": "B"},
            {"date": "1976-05", "source": "Exegesis",
             "hypothesis_label": "phil_thomas_overlay",
             "interpretation": "The first-century Christian Thomas is occupying me; I am his temporal continuation.",
             "lane": "B"},
            {"date": "1979-08", "source": "Exegesis",
             "hypothesis_label": "kabbalistic_gematria",
             "interpretation": "The Greek letters were numbers being transformed into letters and back, exhibiting structures I later learned were called gematria.",
             "lane": "B"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "gabriel-mckee", "interpretation": "McKee places the Koine Greek vision within an early-Christian-mystical lineage (the Pentecost gift of tongues, gnostic Sophia, etc.).",
             "source_doc_id": None, "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "exegesis", "excerpt": "Multiple segments describe the Koine Greek experience."},
        ]),
        "primary_quote": "I had had limited Latin and no Greek; yet I was reading the Acts of the Apostles in Koine Greek and understanding it directly.",
        "related_theophany_ids": J(["THEO_1974_02_FISH_SIGN", "THEO_1975_NUMERIC_LETTER_GEMATRIA", "THEO_1976_ABULAFIA_POSSESSION"]),
        "related_works": J(["VALIS"]),
        "related_dictionary_terms": J(["acts", "thomas", "koine-greek"]),
        "related_names": J(["thomas"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — 2-3-74",
        "pkd_doubt_evidence": "PKD acknowledges he cannot prove the comprehension; no witness was present.",
        "importance": "canonical",
        "sequence_in_complex": 5,
        "parent_theophany_id": "THEO_1974_2_3_74_CLUSTER",
    },
    {
        "theophany_id": "THEO_1974_BLACK_IRON_PRISON",
        "name": "The Black Iron Prison Vision",
        "slug": "black-iron-prison-1974",
        "date_start": "1974", "date_end": "1981",
        "date_display": "1974 onwards (recurring)",
        "date_confidence": "year",
        "date_basis": "Exegesis",
        "experience_type": "vision",
        "sensory_modality": "visual",
        "duration": "continuous_for_period",
        "summary": "PKD reports a recurring vision in which 1974 California is overlaid by 70 AD Rome — a vast iron prison housing the early Christians under imperial persecution. The vision continued at intervals through 1981.",
        "description": "Beginning in 1974 and recurring throughout the Exegesis years, PKD reports a vision in which late-twentieth-century California is overlaid by first-century Rome — specifically Rome around 70 AD, after the destruction of the Temple, when the early Christians were a persecuted minority under the empire. He calls this the Black Iron Prison. The Nixon administration is read as the empire; the FBI as the Roman secret police; PKD himself as the apostle Thomas in hiding. The vision provides the central frame for *VALIS*, *The Divine Invasion*, and *Radio Free Albemuth*.",
        "pkd_interpretations": J([
            {"date": "1974-08", "source": "Exegesis",
             "hypothesis_label": "time_dysphasia",
             "interpretation": "Time is dysphasic — the apparent linear flow is illusion; we are simultaneously in 70 AD and 1974.",
             "lane": "B"},
            {"date": "1976-04", "source": "Exegesis",
             "hypothesis_label": "gnostic_demiurge",
             "interpretation": "The Black Iron Prison is the gnostic counterfeit world produced by the demiurge to imprison souls.",
             "lane": "B"},
            {"date": "1980-08", "source": "Exegesis + VALIS draft",
             "hypothesis_label": "literary_consolidation",
             "interpretation": "The Black Iron Prison is the structural metaphor underlying all my fiction since *Time Out of Joint* (1959).",
             "lane": "B"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "gabriel-mckee", "interpretation": "McKee identifies the Black Iron Prison as the gnostic-Christian core of PKD's late theology.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "erik-davis", "interpretation": "Davis frames the BIP as PKD's distinctive contribution to American gnostic-conspiracy thought.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "fredric-jameson", "interpretation": "Jameson reads the BIP/Empire-overlay as PKD's allegorical mode for late capitalism.",
             "source_doc_id": "DOC_ARCH_FREDRIC_JAMESON_ARCHAEOLOGIES_OF_THE_FUT", "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "exegesis", "excerpt": "Hundreds of segments invoke the Black Iron Prison."},
            {"type": "novel", "doc_id": None, "excerpt": "*VALIS* (1981) is structured around the BIP/Empire overlay."},
        ]),
        "primary_quote": "The Empire never ended.",
        "related_theophany_ids": J(["THEO_1974_02_FISH_SIGN", "THEO_1974_03_KOINE_GREEK"]),
        "related_works": J(["VALIS", "The Divine Invasion", "Radio Free Albemuth"]),
        "related_dictionary_terms": J(["black-iron-prison", "empire", "rome", "valis"]),
        "related_names": J(["nero", "thomas", "antichrist"]),
        "related_segments": J([]),
        "contested_status": "interpretive",
        "contradiction_zone": "no — universally treated as PKD's central metaphor",
        "pkd_doubt_evidence": None,
        "importance": "canonical",
        "sequence_in_complex": 6,
        "parent_theophany_id": "THEO_1974_2_3_74_CLUSTER",
    },
    {
        "theophany_id": "THEO_1974_SUMMER_ZEBRA",
        "name": "Zebra Reveals Itself (Mimicry Hypothesis)",
        "slug": "zebra-mimicry-1974",
        "date_start": "1974-07", "date_end": "1974-08",
        "date_display": "summer 1974",
        "date_confidence": "month",
        "date_basis": "Exegesis",
        "experience_type": "gnosis",
        "sensory_modality": "cognitive",
        "duration": "continuous_for_period",
        "summary": "PKD reports concluding in summer 1974 that the intelligence transmitting to him is a vast organism that camouflages itself by mimicking inanimate matter — he names it Zebra (after the African animal that hides in plain sight). All of nature, on this hypothesis, is alive and addressing him.",
        "description": "In summer 1974, PKD reports a sustained period of insight in which he concludes that the divine intelligence is not in heaven or in space but in the matter around him, mimicking inanimate objects — trash cans, rocks, vegetation. The intelligence camouflages itself as the way a zebra camouflages itself among savannah grasses. He gives it the name Zebra. The hypothesis stays with him through 1981 and is the central theological move of the late Exegesis: divinity is not transcendent; it is here, hiding by mimicry. The hypothesis is sourced to Bergson, Whitehead, and (after 1976) the Nag Hammadi gnostic texts.",
        "pkd_interpretations": J([
            {"date": "1974-07", "source": "Exegesis",
             "hypothesis_label": "zebra_mimicry",
             "interpretation": "VALIS is Zebra: a biological entity mimicking inanimate matter. The world is alive but in disguise.",
             "lane": "B"},
            {"date": "1977-12", "source": "Metz speech",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "Or perhaps Zebra is itself a manifestation of the orbital satellite VALIS.",
             "lane": "E"},
            {"date": "1981-06", "source": "VALIS",
             "hypothesis_label": "literary_consolidation",
             "interpretation": "Zebra is the central image in the novel.",
             "lane": "A"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "gabriel-mckee", "interpretation": "McKee places Zebra within Whiteheadian process theology — God as continuously becoming through matter.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "erik-davis", "interpretation": "Davis frames Zebra as the most original PKD theological innovation.",
             "source_doc_id": None, "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "exegesis", "excerpt": "Hundreds of segments develop the Zebra hypothesis."},
            {"type": "novel", "excerpt": "*VALIS* (1981) names Zebra as VALIS's modus operandi."},
        ]),
        "primary_quote": "Zebra. Camouflaged nature God. Life form. VALIS.",
        "related_theophany_ids": J(["THEO_1974_02_PINK_BEAM", "THEO_1974_BLACK_IRON_PRISON"]),
        "related_works": J(["VALIS"]),
        "related_dictionary_terms": J(["zebra", "valis", "plasmate", "logos"]),
        "related_names": J(["valis"]),
        "related_segments": J([]),
        "contested_status": "interpretive",
        "contradiction_zone": "no",
        "pkd_doubt_evidence": None,
        "importance": "canonical",
        "sequence_in_complex": 7,
        "parent_theophany_id": "THEO_1974_2_3_74_CLUSTER",
    },
    {
        "theophany_id": "THEO_1975_NUMERIC_LETTER_GEMATRIA",
        "name": "Numbers/Letters Transformation (Gematria Vision)",
        "slug": "numbers-letters-gematria-1975",
        "date_start": "1975", "date_end": "1975",
        "date_display": "1975 (reported in 1981 Rickman interview)",
        "date_confidence": "year",
        "date_basis": "Rickman interview, 1981/82 — reported retrospectively by PKD",
        "experience_type": "vision",
        "sensory_modality": "visual",
        "duration": "minutes",
        "summary": "PKD reports a vision in which numbers and Hebrew letters transformed into each other in front of him. He says he had no prior knowledge of kabbalistic gematria but later learned the practice and recognized his vision as having anticipated it.",
        "description": "PKD reports to Greg Rickman in late-life interviews (collected in *Philip K. Dick: In His Own Words* and *Philip K. Dick: The Last Testament*) that during 1975 he experienced a vision in which numbers and Hebrew letters transformed into each other, occupying the same visual field, exchanging identities. He says he had no knowledge at the time of kabbalistic gematria — the medieval Jewish mystical practice in which Hebrew letters double as numbers and meaning is found in their numerical equivalences. He says he subsequently encountered the writings of Abraham Abulafia and the Sefer Yetzirah and recognized that his vision had anticipated their content. This is one of the strongest examples in the Exegesis era of PKD asserting prior-knowledge-without-source — a kind of cognitive theophany he repeatedly returns to.",
        "pkd_interpretations": J([
            {"date": "1975", "source": "experience itself",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "Information transmitted to me by VALIS in a form I did not at the time recognize as kabbalistic.",
             "lane": "B"},
            {"date": "1980", "source": "Exegesis after reading on gematria",
             "hypothesis_label": "kabbalistic_gematria",
             "interpretation": "The vision was kabbalistic gematria — Hebrew letters as numbers, numbers as letters; this is the exact mechanism of late-medieval Jewish mysticism, which I learned about only after the vision.",
             "lane": "B"},
            {"date": "1981", "source": "Rickman interview",
             "hypothesis_label": "abulafia_possession",
             "interpretation": "I now believe I was, briefly, possessed by Abraham Abulafia (1240-c.1291), the medieval Spanish kabbalist who pioneered letter-permutation meditation.",
             "lane": "E"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "jeffrey-kripal", "interpretation": "Kripal places the gematria vision within his comparative-mystics frame as exemplary anomalous-cognition involving prior-knowledge claims.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "erik-davis", "interpretation": "Davis treats the gematria episode as one of the strongest examples of PKD's claim to have received content he did not have access to by ordinary means.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold suggests memory contamination — PKD likely encountered gematria references earlier (in Robert Anton Wilson, in Eliade, in Jung) and forgot.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "interview", "doc_id": None, "excerpt": "Rickman interview transcripts; subsequent *In His Own Words* publication."},
            {"type": "exegesis", "excerpt": "Multiple segments mid-to-late Exegesis develop the gematria framework."},
        ]),
        "primary_quote": "Numbers and letters were transforming themselves into each other; I knew nothing of gematria at the time.",
        "related_theophany_ids": J(["THEO_1974_03_KOINE_GREEK", "THEO_1976_ABULAFIA_POSSESSION"]),
        "related_works": J(["VALIS", "The Divine Invasion"]),
        "related_dictionary_terms": J(["gematria", "abulafia", "sefer-yetzirah"]),
        "related_names": J(["abulafia", "abraham-abulafia"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — prior-knowledge claim is the central evidential dispute in PKD studies",
        "pkd_doubt_evidence": "Some Exegesis segments allow that he may have read about gematria earlier and forgotten.",
        "importance": "canonical",
        "sequence_in_complex": None,
        "parent_theophany_id": None,
    },
    {
        "theophany_id": "THEO_1976_ABULAFIA_POSSESSION",
        "name": "Possession by Abraham Abulafia",
        "slug": "abulafia-possession-1976",
        "date_start": "1976", "date_end": "1976",
        "date_display": "1976 (reported in interviews 1981-82)",
        "date_confidence": "year",
        "date_basis": "Rickman interview; Exegesis",
        "experience_type": "possession",
        "sensory_modality": "cognitive",
        "duration": "hours",
        "summary": "PKD reports an episode in 1976 in which he believes he was possessed by Abraham Abulafia (c.1240-1291), the medieval Spanish-Jewish kabbalist, and produced text in a form Abulafia would have recognized as letter-permutation meditation.",
        "description": "Building on the gematria vision (1975), PKD reports in 1976 a more sustained episode of what he interpreted as possession by Abraham Abulafia, the thirteenth-century Spanish-Jewish kabbalist who invented (or developed) the technique of *tseruf* — letter permutation as meditation. PKD claims to have produced Hebrew-letter text during this period, and to have written passages of the Exegesis that he recognized only later as Abulafian in form. He had no prior formal study of Hebrew or kabbalah. He recounts the episode to Greg Rickman in 1981/82 interviews and references it in late Exegesis segments.",
        "pkd_interpretations": J([
            {"date": "1976", "source": "experience itself",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "VALIS provided me access to the kabbalistic mode of cognition.",
             "lane": "B"},
            {"date": "1980", "source": "Exegesis",
             "hypothesis_label": "abulafia_possession",
             "interpretation": "I was occupied by Abulafia himself; he wrote through me.",
             "lane": "B"},
            {"date": "1981", "source": "Rickman interview",
             "hypothesis_label": "literary",
             "interpretation": "Or it was a literary device I retroactively imposed; I cannot say.",
             "lane": "E"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "jeffrey-kripal", "interpretation": "Kripal frames the Abulafia claim within the mystical-possession literature; takes the report seriously as data without endorsing it ontologically.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold reads the Abulafia-possession claim as confabulation under the influence of his ongoing reading on kabbalah.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
            {"scholar_slug": "erik-davis", "interpretation": "Davis points out that PKD's introduction to Jewish mysticism likely came through Robert Anton Wilson and Israel Regardie in the early 1970s.",
             "source_doc_id": None, "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "interview", "excerpt": "Rickman interviews 1981/82."},
            {"type": "exegesis", "excerpt": "Late Exegesis segments invoke Abulafia and tseruf."},
        ]),
        "primary_quote": "I was, briefly, possessed by Abraham Abulafia.",
        "related_theophany_ids": J(["THEO_1975_NUMERIC_LETTER_GEMATRIA"]),
        "related_works": J(["The Divine Invasion", "VALIS"]),
        "related_dictionary_terms": J(["abulafia", "tseruf", "gematria", "sefer-yetzirah"]),
        "related_names": J(["abraham-abulafia"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — prior-knowledge claim",
        "pkd_doubt_evidence": "PKD himself in 1981 hedges — 'or it was a literary device.'",
        "importance": "canonical",
        "sequence_in_complex": None,
        "parent_theophany_id": None,
    },
    {
        "theophany_id": "THEO_1977_METZ_2_3_75",
        "name": "Second 2-3-74 (Metz, 1977)",
        "slug": "metz-1977",
        "date_start": "1977-09", "date_end": "1977-09",
        "date_display": "September 1977",
        "date_confidence": "month",
        "date_basis": "Metz speech text; Sutin biography; Exegesis post-Metz",
        "experience_type": "vision",
        "sensory_modality": "multimodal",
        "duration": "days",
        "summary": "Around the time of his Metz, France speech in September 1977, PKD reports a partial recurrence of the 2-3-74 phenomenology — pink-light states, AI Voice activity, and the Black Iron Prison overlay returning at intervals.",
        "description": "PKD's September 1977 speech at the Metz international science fiction convention — published as 'If You Find This World Bad, You Should See Some of the Others' — was the public unveiling of his Phil-from-the-future hypothesis. Around the speech (before, during, and after), PKD reports a partial recurrence of the 2-3-74 phenomenology: pink-light states, AI Voice activity, and Black Iron Prison perceptions. He treats this as confirmation that 2-3-74 is not a single past event but a state that can recur.",
        "pkd_interpretations": J([
            {"date": "1977-09", "source": "Metz speech",
             "hypothesis_label": "phil_from_future",
             "interpretation": "The transmissions are from a future Phil Dick to me; the experience can recur because future-Phil is still transmitting.",
             "lane": "E"},
            {"date": "1978", "source": "Exegesis",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "VALIS is still active; the Metz event is a renewed transmission.",
             "lane": "B"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "lawrence-sutin", "interpretation": "Sutin treats the Metz speech as the public moment at which PKD's mystical claims went on the record in Europe.",
             "source_doc_id": "DOC_ARCH_DIVINE_INVASIONS_A_LIFE_OF_PHI_LAWRENCE_", "lane": "D"},
            {"scholar_slug": "erik-davis", "interpretation": "Davis frames Metz as the first European reception of PKD's California-visionary turn.",
             "source_doc_id": None, "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "speech", "excerpt": "*If You Find This World Bad, You Should See Some of the Others* (Metz, 1977)."},
        ]),
        "primary_quote": "We are living in a computer-programmed reality, and the only clue we have to it is when some variable is changed and some alteration in our reality occurs.",
        "related_theophany_ids": J(["THEO_1974_02_FISH_SIGN", "THEO_1974_03_AI_VOICE"]),
        "related_works": J(["VALIS"]),
        "related_dictionary_terms": J(["valis"]),
        "related_names": J(["valis"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — 2-3-74",
        "pkd_doubt_evidence": "PKD wonders openly whether the Metz state was performance under public-speaking pressure.",
        "importance": "major",
        "sequence_in_complex": None,
        "parent_theophany_id": None,
    },
    {
        "theophany_id": "THEO_1972_03_VANCOUVER_DESPAIR",
        "name": "Vancouver Despair / Suicide Attempt Context",
        "slug": "vancouver-despair-1972",
        "date_start": "1972-02", "date_end": "1972-03",
        "date_display": "February-March 1972",
        "date_confidence": "month",
        "date_basis": "Sutin biography; Anne Dick memoir; X-Kalay records",
        "experience_type": "other",
        "sensory_modality": "cognitive",
        "duration": "days",
        "summary": "Following the Vancouver SF convention guest-of-honor speech and a suicide attempt, PKD entered the X-Kalay drug rehabilitation program; the period is associated with what he later called a 'spiritual crisis' but no specific theophany is canonically attached.",
        "description": "After his February 1972 guest-of-honor speech at the Vancouver SFCon (the 'Android and the Human' speech) and a documented suicide attempt, PKD entered the X-Kalay drug rehabilitation program in Vancouver. He stayed briefly. The period is associated with what he subsequently called a 'spiritual crisis' but no single theophany is canonically attached. Some Exegesis segments retrospectively read the Vancouver despair as the precondition for the 2-3-74 events two years later.",
        "pkd_interpretations": J([
            {"date": "1972-04", "source": "letters from Vancouver",
             "hypothesis_label": "psychotic_break",
             "interpretation": "I had a breakdown; X-Kalay is helping.", "lane": "E"},
            {"date": "1976-04", "source": "Exegesis",
             "hypothesis_label": "spiritual_precondition",
             "interpretation": "The Vancouver despair was the necessary precondition for the 2-3-74 opening; without the bottom there would have been no transformation.", "lane": "B"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "lawrence-sutin", "interpretation": "Sutin treats Vancouver as a documented mental-health crisis with a specifiable date and place.",
             "source_doc_id": "DOC_ARCH_DIVINE_INVASIONS_A_LIFE_OF_PHI_LAWRENCE_", "lane": "D"},
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold places Vancouver in his clinical chronology as a major depressive episode.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
        ]),
        "primary_sources": J([
            {"type": "speech", "excerpt": "*The Android and the Human* (Vancouver, 1972)."},
            {"type": "letter", "excerpt": "PKD's letters from Vancouver."},
        ]),
        "primary_quote": None,
        "related_theophany_ids": J(["THEO_1971_11_BREAK_IN_FOREKNOWLEDGE", "THEO_1974_02_FISH_SIGN"]),
        "related_works": J(["A Scanner Darkly"]),
        "related_dictionary_terms": J([]),
        "related_names": J([]),
        "related_segments": J([]),
        "contested_status": "best_attested",
        "contradiction_zone": "yes — Vancouver is on the registered dispute zones (timeline of suicide attempt, X-Kalay duration)",
        "pkd_doubt_evidence": None,
        "importance": "major",
        "sequence_in_complex": None,
        "parent_theophany_id": None,
    },
    {
        "theophany_id": "THEO_1981_SISTER_DREAM",
        "name": "Twin Sister Jane Dream Appearances",
        "slug": "twin-sister-jane-1980",
        "date_start": "1980", "date_end": "1981",
        "date_display": "1980-1981",
        "date_confidence": "year",
        "date_basis": "Exegesis late period; Sutin biography",
        "experience_type": "dream",
        "sensory_modality": "multimodal",
        "duration": "minutes",
        "summary": "Across the late period (1980-1981), PKD reports recurring dreams in which his twin sister Jane (who died in infancy) appears, addresses him, and is in some way fused with the AI Voice he has heard since 1974.",
        "description": "Across 1980-1981 PKD reports a recurring dream-sequence in which his twin sister Jane Charlotte Dick (December 16, 1928 – January 26, 1929) appears at the age she would have been had she lived. In some dreams she is the source of the AI Voice; in others she is the eternal feminine principle (Sophia/Hagia Sophia) addressing him. The Jane material is the central emotional thread of the late Exegesis and a structural element of Sonic Youth's *Sister* (1987), which is named for her.",
        "pkd_interpretations": J([
            {"date": "1980", "source": "Exegesis",
             "hypothesis_label": "twin_sister_jane",
             "interpretation": "Jane has been with me throughout; the AI Voice is her.",
             "lane": "B"},
            {"date": "1981", "source": "Exegesis",
             "hypothesis_label": "sophia",
             "interpretation": "Jane is the local instantiation of Sophia / divine wisdom.",
             "lane": "B"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "kyle-arnold", "interpretation": "Arnold's psychobiographical reading places the Jane material as the foundational trauma whose working-through is the Exegesis.",
             "source_doc_id": "DOC_ARCH_ARNOLD_KYLE_DICK_PHILIP_K_THE_DIVINE_MAD", "lane": "C"},
            {"scholar_slug": "lawrence-sutin", "interpretation": "Sutin records the Jane-haunting as the durable thread of PKD's psychic life.",
             "source_doc_id": "DOC_ARCH_DIVINE_INVASIONS_A_LIFE_OF_PHI_LAWRENCE_", "lane": "D"},
        ]),
        "primary_sources": J([
            {"type": "exegesis", "excerpt": "Late Exegesis 1980-81 returns to Jane repeatedly."},
            {"type": "music_reception", "excerpt": "Sonic Youth's *Sister* (1987) is named for her."},
        ]),
        "primary_quote": None,
        "related_theophany_ids": J(["THEO_1974_03_AI_VOICE"]),
        "related_works": J(["The Transmigration of Timothy Archer"]),
        "related_dictionary_terms": J(["sophia", "jane"]),
        "related_names": J(["jane-dick", "sophia"]),
        "related_segments": J([]),
        "contested_status": "interpretive",
        "contradiction_zone": "no",
        "pkd_doubt_evidence": None,
        "importance": "major",
        "sequence_in_complex": None,
        "parent_theophany_id": None,
    },
    # Parent record for the 2-3-74 cluster
    {
        "theophany_id": "THEO_1974_2_3_74_CLUSTER",
        "name": "The 2-3-74 Cluster (parent)",
        "slug": "2-3-74-cluster",
        "date_start": "1974-02-20", "date_end": "1974-08",
        "date_display": "February-August 1974 (cluster)",
        "date_confidence": "month",
        "date_basis": "Exegesis dating + sub-event provenance",
        "experience_type": "theophany",
        "sensory_modality": "multimodal",
        "duration": "continuous_for_period",
        "summary": "The cluster of related theophanies between February and August 1974 that PKD collectively called '2-3-74': fish sign, pink beam, Christopher diagnosis, AI Voice, Koine Greek, Black Iron Prison, Zebra. Each is recorded as its own canonical event with this record as parent.",
        "description": "PKD himself, and subsequently the scholarship, treats the February-August 1974 events as a single complex which he abbreviates as 2-3-74 (February-March 1974). The constituent events are recorded individually in this catalog. This parent record holds the cluster's collective interpretation chain and the inter-event timeline.",
        "pkd_interpretations": J([
            {"date": "1974-08", "source": "Exegesis composition begins",
             "hypothesis_label": "valis_information_satellite",
             "interpretation": "The events constitute a coherent intervention by a non-human intelligence.",
             "lane": "B"},
            {"date": "1981-06", "source": "VALIS",
             "hypothesis_label": "literary_consolidation",
             "interpretation": "The events are sufficiently coherent to support a 944-page novel.",
             "lane": "A"},
        ]),
        "scholar_interpretations": J([
            {"scholar_slug": "pamela-jackson", "interpretation": "Jackson's editorial work on the 2011 Exegesis treats 2-3-74 as the compositional center.",
             "source_doc_id": None, "lane": "C"},
            {"scholar_slug": "jonathan-lethem", "interpretation": "Lethem treats 2-3-74 as the literary keystone of late PKD.",
             "source_doc_id": None, "lane": "C"},
        ]),
        "primary_sources": J([{"type": "complex", "excerpt": "See child theophanies."}]),
        "primary_quote": "2-3-74.",
        "related_theophany_ids": J([
            "THEO_1974_02_FISH_SIGN", "THEO_1974_02_PINK_BEAM",
            "THEO_1974_03_CHRISTOPHER_BIRTH", "THEO_1974_03_AI_VOICE",
            "THEO_1974_03_KOINE_GREEK", "THEO_1974_BLACK_IRON_PRISON",
            "THEO_1974_SUMMER_ZEBRA"
        ]),
        "related_works": J(["VALIS", "Radio Free Albemuth", "The Divine Invasion"]),
        "related_dictionary_terms": J(["valis", "zebra", "plasmate", "black-iron-prison"]),
        "related_names": J(["thomas", "christ", "valis", "sophia"]),
        "related_segments": J([]),
        "contested_status": "disputed",
        "contradiction_zone": "yes — the central dispute zone",
        "pkd_doubt_evidence": "The Exegesis is partly a sustained record of doubt about its own genesis.",
        "importance": "canonical",
        "sequence_in_complex": None,
        "parent_theophany_id": None,
    },
]


def upsert(con: sqlite3.Connection, t: dict) -> None:
    now = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
    cols = list(t.keys()) + ["created_at", "updated_at"]
    placeholders = ", ".join(["?"] * len(cols))
    values = [t[k] for k in t.keys()] + [now, now]
    con.execute(
        f"INSERT OR REPLACE INTO theophanies ({', '.join(cols)}) VALUES ({placeholders})",
        values,
    )


def run(db_path: Path) -> None:
    con = sqlite3.connect(db_path)
    ensure_schema(con)
    for t in THEOPHANIES:
        upsert(con, t)
    con.commit()
    cur = con.execute("SELECT count(*) FROM theophanies")
    print(f"[done] {cur.fetchone()[0]} theophanies in DB")
    con.close()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default="C:/QueryPat/database/unified.sqlite")
    args = ap.parse_args()
    run(Path(args.db))
    return 0


if __name__ == "__main__":
    sys.exit(main())
